"""empty message

Revision ID: 43882cb406ad
Revises: b2cff11efea2
Create Date: 2023-10-05 21:49:46.567735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43882cb406ad'
down_revision = 'b2cff11efea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=3000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=3000),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
