"""empty message

Revision ID: b2cff11efea2
Revises: 2332c293110f
Create Date: 2023-09-15 22:29:48.250712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cff11efea2'
down_revision = '2332c293110f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('blog_userId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('blog_userId_fkey', 'user', ['userId'], ['id'])
        batch_op.drop_column('fecha')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
