# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: public

jobs:
# Please do not rename this job
  build-project:
    name: build fisioInMadrid
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Build Node assets
        env:
          BACKEND_URL: https://obscure-carnival-44rgq5prrjqfq5p7-3001.app.github.dev
          BASENAME: /
          CI: true
          DATABASE_URL: postgres://gitpod:postgres@localhost:5432/example
          DEBUG: TRUE
          FLASK_APP: src/app.py
          FLASK_APP_KEY: any key works
          FLASK_DEBUG: 1
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 5f0d40c8-00d8-4dfd-b076-79b80ae118f5
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/fisioInMadrid/config.yaml
          action: upload
